name: Publish To Wordpress

on:
  workflow_dispatch:
    inputs:
      updateDescription:
        description: 'Update Description'
        required: true
        default: 'updated'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y subversion
          svn checkout --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}} ${{secrets.SVN_URL}} wp-plugin --depth empty
          svn add --force wp-plugin/*
          svn update wp-plugin/* --accept mine-full
          svn resolve wp-plugin --accept working -R
          svn commit wp-plugin -m "${{github.event.inputs.updateDescription}}" --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}}
